[2016-12-20 09:25:27 +0000] [19478] [INFO] Starting gunicorn 19.6.0
[2016-12-20 09:25:27 +0000] [19478] [INFO] Listening at: http://127.0.0.1:8000 (19478)
[2016-12-20 09:25:27 +0000] [19478] [INFO] Using worker: sync
[2016-12-20 09:25:27 +0000] [19483] [INFO] Booting worker with pid: 19483
[2016-12-20 09:25:27 +0000] [19483] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named app
[2016-12-20 09:25:27 +0000] [19483] [INFO] Worker exiting (pid: 19483)
[2016-12-20 09:25:27 +0000] [19478] [INFO] Shutting down: Master
[2016-12-20 09:25:27 +0000] [19478] [INFO] Reason: Worker failed to boot.
[2016-12-20 09:25:37 +0000] [19485] [INFO] Starting gunicorn 19.6.0
[2016-12-20 09:25:37 +0000] [19485] [INFO] Listening at: http://127.0.0.1:8000 (19485)
[2016-12-20 09:25:37 +0000] [19485] [INFO] Using worker: sync
[2016-12-20 09:25:37 +0000] [19490] [INFO] Booting worker with pid: 19490
[2016-12-20 09:25:37 +0000] [19490] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named app
[2016-12-20 09:25:37 +0000] [19490] [INFO] Worker exiting (pid: 19490)
[2016-12-20 09:25:37 +0000] [19485] [INFO] Shutting down: Master
[2016-12-20 09:25:37 +0000] [19485] [INFO] Reason: Worker failed to boot.
